import { CmsProduct, CustomerProfile, PredefinedPrompt, PromoCode } from "./types";

export const DEFAULT_PROMPTS: PredefinedPrompt[] = [
  {
    id: "prompt_longevity_01",
    title: "Executive Longevity & Vitality Protocol",
    category: "wellness-longevity",
    description: "Deep bio-lifestyle analysis tailoring circadian health, nutrition, and recovery routines with strict pronoun consistency.",
    systemDirective: "You are the Lead Longevity Clinician & Human Performance Specialist for PersonaFlow AI. Analyze the customer's profile with precision. Ensure every pronoun reference strictly respects their chosen pronouns ({{pronouns.subject}} / {{pronouns.object}} / {{pronouns.possessive}}). Output structured recommendations with actionable daily protocols.",
    userTemplate: "Generate an authoritative, personalized Longevity Protocol for {{name}}. {{pronouns.Subject}} {{pronouns.has_have}} committed to {{commitment_hrs}} per week in {{category}}. Primary goals: {{goals}}. Focus areas: {{focus_areas}}. Tone: {{tone}}. Ensure {{pronouns.possessive}} report includes exact daily timing, evidence-based metrics, and a 90-day trajectory.",
    variables: ["{{name}}", "{{pronouns.Subject}}", "{{pronouns.possessive}}", "{{goals}}", "{{commitment_hrs}}", "{{focus_areas}}", "{{tone}}"],
    activeModel: "gpt-4o-mini (OpenAI) / gemini-2.0-flash (Google)",
  },
  {
    id: "prompt_career_02",
    title: "Strategic Executive Positioning Blueprint",
    category: "executive-career",
    description: "High-leverage leadership career trajectory mapping, negotiation leverage, and 12-month board/executive roadmaps.",
    systemDirective: "You are an Elite Executive Search Partner & C-Suite Career Strategist. Formulate a confidential executive briefing. Maintain impeccable grammatical agreement for {{pronouns.subject}} (using '{{pronouns.subject}} {{pronouns.is_are}}' and '{{pronouns.possessive}} team').",
    userTemplate: "Formulate an Executive Leadership Dossier for {{name}}. {{pronouns.Subject}} currently seeks to master: {{goals}}. Experience tier: {{experience_level}}. Focus areas: {{focus_areas}}. Tone: {{tone}}. Provide {{pronouns.object}} with three high-impact leverage points and a phased organizational roadmap.",
    variables: ["{{name}}", "{{pronouns.Subject}}", "{{pronouns.object}}", "{{pronouns.possessive}}", "{{goals}}", "{{experience_level}}", "{{focus_areas}}"],
    activeModel: "gpt-4o-mini (OpenAI) / gemini-2.0-flash (Google)",
  },
  {
    id: "prompt_wealth_03",
    title: "Autonomous Financial Architecture Strategy",
    category: "financial-blueprint",
    description: "Wealth preservation, tax velocity, automated asset allocation, and passive income compounding frameworks.",
    systemDirective: "You are a Private Family Office Quantitative Wealth Architect. Formulate an actionable personal financial roadmap. Always adhere to {{pronouns.possessive}} stated risk tolerance and pronoun specifications.",
    userTemplate: "Build an institutional-grade Personal Wealth Blueprint for {{name}}. {{pronouns.Subject}} {{pronouns.does_do}} plan to optimize: {{goals}}. Tier: {{budget_tier}}. Commitment: {{commitment_hrs}}. Outline strategic capital allocation, tax shielding principles, and milestone targets tailored directly to {{pronouns.possessive}} profile.",
    variables: ["{{name}}", "{{pronouns.Subject}}", "{{pronouns.possessive}}", "{{goals}}", "{{budget_tier}}", "{{commitment_hrs}}"],
    activeModel: "gpt-4o-mini (OpenAI) / gemini-2.0-flash (Google)",
  },
  {
    id: "prompt_life_04",
    title: "Holistic 90-Day Life Strategy & Focus Audit",
    category: "life-strategy",
    description: "Cross-domain lifestyle optimization balancing energy, relationships, deep work, and personal legacy.",
    systemDirective: "You are a Master Life Architect and Cognitive Strategist. Deliver a compassionate yet razor-sharp life assessment. Ensure {{pronouns.subject}} feel completely understood with flawless pronoun usage throughout.",
    userTemplate: "Conduct a comprehensive Life Strategy Audit for {{name}}. Highlight {{pronouns.possessive}} primary strengths and address friction in: {{goals}}. Focus areas: {{focus_areas}}. Deliver a high-clarity 90-day action sprint.",
    variables: ["{{name}}", "{{pronouns.Subject}}", "{{pronouns.possessive}}", "{{goals}}", "{{focus_areas}}"],
    activeModel: "gpt-4o-mini (OpenAI) / gemini-2.0-flash (Google)",
  },
];

export const DEFAULT_PRODUCTS: CmsProduct[] = [
  {
    id: "prod_01",
    name: "Executive Longevity & Biomarker Blueprint",
    slug: "executive-longevity-blueprint",
    category: "wellness-longevity",
    price: 149,
    billingInterval: "one-time",
    status: "active",
    description: "Comprehensive 18-page personalized biomarker and circadian health roadmap with daily chronotype schedules.",
    features: ["Personalized Chrono-Schedule", "Biomarker Target Range", "Supplement Stack Matrix", "Instant PDF Download"],
    associatedPromptId: "prompt_longevity_01",
    badge: "Bestseller",
  },
  {
    id: "prod_02",
    name: "High-Performance Leadership & Board Dossier",
    slug: "leadership-board-dossier",
    category: "executive-career",
    price: 199,
    billingInterval: "one-time",
    status: "active",
    description: "Confidential executive career trajectory assessment, compensation negotiation frameworks, and 12-month positioning roadmap.",
    features: ["C-Suite Trajectory Map", "Compensation Leverage Model", "Board Readout Template", "SMS Weekly Prompts"],
    associatedPromptId: "prompt_career_02",
    badge: "Executive Tier",
  },
  {
    id: "prod_03",
    name: "Private Wealth & Capital Velocity Architecture",
    slug: "private-wealth-architecture",
    category: "financial-blueprint",
    price: 249,
    billingInterval: "one-time",
    status: "active",
    description: "Institutional-grade wealth distribution, tax-efficient velocity planning, and automated liquidity rules.",
    features: ["Capital Allocation Graph", "Tax Shielding Framework", "Passive Cashflow Forecast", "Dedicated AI Concierge"],
    associatedPromptId: "prompt_wealth_03",
    badge: "Institutional",
  },
  {
    id: "prod_04",
    name: "PersonaFlow VIP Monthly Retainer & Concierge",
    slug: "personaflow-vip-subscription",
    category: "life-strategy",
    price: 49,
    billingInterval: "monthly",
    status: "active",
    description: "Ongoing continuous monthly report re-calibrations, unlimited profile-aware AI chatbot queries, and automated SMS alerts.",
    features: ["Unlimited Monthly Re-runs", "24/7 Profile-Aware Chat", "Priority SMS Notifications", "New Product Early Access"],
    associatedPromptId: "prompt_life_04",
    badge: "Popular Plan",
  },
];

export const DEFAULT_PROMO_CODES: PromoCode[] = [
  {
    code: "WELCOME50",
    discountPercent: 50,
    validUntil: "2026-12-31",
    maxRedemptions: 500,
    timesRedeemed: 142,
    status: "active",
  },
  {
    code: "FOUNDERVIP",
    discountPercent: 100,
    validUntil: "2026-10-31",
    maxRedemptions: 50,
    timesRedeemed: 12,
    status: "active",
  },
  {
    code: "ALBEMARLE2026",
    discountPercent: 30,
    validUntil: "2026-11-30",
    maxRedemptions: 1000,
    timesRedeemed: 67,
    status: "active",
  },
  {
    code: "SUMMER25",
    discountPercent: 25,
    validUntil: "2026-08-31",
    maxRedemptions: 200,
    timesRedeemed: 200,
    status: "expired",
  },
];

export const SAMPLE_PROFILES: CustomerProfile[] = [
  {
    id: "prof_01",
    fullName: "Morgan Vance",
    email: "morgan.vance@enterprise-health.org",
    phone: "+1 (555) 234-8901",
    pronouns: "they/them",
    selectedCategory: "wellness-longevity",
    primaryGoals: ["Optimize Deep Sleep & REM", "Lower Resting Heart Rate by 6 bpm", "Mitigate Cortisol Spikes During M&A"],
    lifestyleFactors: {
      weeklyCommitmentHrs: 6,
      focusAreas: ["Sleep Architecture", "Cold Thermogenesis", "Zone 2 Cardiovascular", "Precision Fasting"],
      budgetTier: "Executive",
      primaryMotivation: "Sustained executive vitality without midday cognitive crash",
    },
    experienceLevel: "intermediate",
    tonePreference: "direct-analytical",
    predefinedPromptId: "prompt_longevity_01",
    endpointTarget: "dual-llm-fallback",
    notificationPreferences: {
      sms: true,
      email: true,
      newsletter: true,
    },
    twoFactorEnabled: true,
  },
  {
    id: "prof_02",
    fullName: "Dr. Elena Rostova",
    email: "elena.rostova@bioventure.io",
    phone: "+1 (555) 345-6712",
    pronouns: "she/her",
    selectedCategory: "executive-career",
    primaryGoals: ["Ascend from VP to Managing Partner", "Secure 2 Biotech Advisory Board Seats", "Keynote at Global Life Sciences Summit"],
    lifestyleFactors: {
      weeklyCommitmentHrs: 8,
      focusAreas: ["Executive Presence", "Venture Governance", "Thought Leadership", "Deal Flow Expansion"],
      budgetTier: "Executive",
      primaryMotivation: "Positioning for fund partner governance within 12 months",
    },
    experienceLevel: "expert",
    tonePreference: "inspirational-visionary",
    predefinedPromptId: "prompt_career_02",
    endpointTarget: "dual-llm-fallback",
    notificationPreferences: {
      sms: true,
      email: true,
      newsletter: false,
    },
    twoFactorEnabled: true,
  },
  {
    id: "prof_03",
    fullName: "David Sterling Chen",
    email: "david.chen@sterling-holdings.co",
    phone: "+1 (555) 901-2384",
    pronouns: "he/him",
    selectedCategory: "financial-blueprint",
    primaryGoals: ["Establish Family Dynasty Trust", "Shield Real Estate Portfolio from Bracket Drift", "Diversify Angel Venture Exits"],
    lifestyleFactors: {
      weeklyCommitmentHrs: 4,
      focusAreas: ["Tax Structuring", "Private Credit Pools", "Estate Transition", "Liquid Yield Engines"],
      budgetTier: "Executive",
      primaryMotivation: "Multi-generational wealth insulation and liquidity optimization",
    },
    experienceLevel: "intermediate",
    tonePreference: "direct-analytical",
    predefinedPromptId: "prompt_wealth_03",
    endpointTarget: "dual-llm-fallback",
    notificationPreferences: {
      sms: false,
      email: true,
      newsletter: true,
    },
    twoFactorEnabled: false,
  },
];
