"use client";

import React, { useState, useEffect } from "react";
import { Navbar } from "@/components/Navbar";
import { BentoKpis } from "@/components/BentoKpis";
import { WorkflowCanvas } from "@/components/WorkflowCanvas";
import { PersonaStudio } from "@/components/PersonaStudio";
import { PdfReportPreview } from "@/components/PdfReportPreview";
import { ProfileAwareChatbot } from "@/components/ProfileAwareChatbot";
import { CmsCatalogWorkbench } from "@/components/CmsCatalogWorkbench";
import { AccountSecurityCenter } from "@/components/AccountSecurityCenter";
import { ExecutionLogDrawer, LogEntry } from "@/components/ExecutionLogDrawer";
import { BlueprintExporter } from "@/components/BlueprintExporter";
import { RoiCostCalculator } from "@/components/RoiCostCalculator";
import { ChaosOutageSimulator } from "@/components/ChaosOutageSimulator";
import { Footer } from "@/components/Footer";

import { CustomerProfile, PersonalizedReport } from "@/lib/types";
import { SAMPLE_PROFILES } from "@/lib/defaultData";
import {
  Sparkles,
  Zap,
  User,
  CheckCircle2,
  Cpu,
  Layers,
  FileText,
  ShieldCheck,
  AlertCircle,
  ArrowRight,
} from "lucide-react";

// Pre-seeded initial dossier so the preview renders instantly
const INITIAL_REPORT: PersonalizedReport = {
  id: "rep_init_01",
  reportCode: "PF-2026-9812",
  title: "Personalized Executive Longevity & Biomarker Dossier",
  generatedAt: "Sep 15, 2026",
  customerName: SAMPLE_PROFILES[0].fullName,
  pronounTag: `${SAMPLE_PROFILES[0].pronouns} (verified agreement)`,
  summary: `${SAMPLE_PROFILES[0].fullName} has structured an intensive 6-hour weekly wellness protocol targeting deep sleep restoration, circadian synchronization, and cortisol mitigation during high-stakes executive transitions. Their biomarker trajectory indicates optimal response to zone-2 cardiovascular training and cold thermogenesis.`,
  coreInsights: [
    {
      title: "Circadian Rhythm & REM Phase Optimization",
      score: 94,
      description: "Analysis indicates their current sleep architecture benefits significantly from morning 10,000-lux photon exposure within 30 minutes of waking.",
      actionItem: "Anchor waking time at 06:15 AM with immediate cold hydration and 15 minutes of outdoor sunlight.",
      statusBadge: "OPTIMAL",
    },
    {
      title: "Cortisol Spike Attenuation During M&A Sprints",
      score: 78,
      description: "Cardiovascular telemetry correlates midday executive meetings with sustained sympathetic tone elevation.",
      actionItem: "Implement dual physiological sigh protocol (2 deep inhales + extended exhalation) prior to board negotiations.",
      statusBadge: "PRIORITY",
    },
    {
      title: "Zone-2 Mitochondrial Density Baseline",
      score: 86,
      description: "Their weekly 6-hour commitment permits 3 targeted 45-minute aerobic sessions below lactate threshold.",
      actionItem: "Schedule stationary cycling blocks on Tuesday, Thursday, and Saturday mornings at 122–134 bpm target HR.",
      statusBadge: "OPTIMAL",
    },
  ],
  personalizedRoadmap: [
    {
      phase: "Phase 1: Foundation & Baseline",
      timeline: "Days 1 – 30",
      milestone: "Circadian Lock & Sleep Stability",
      deliverables: [
        "Consistent 06:15 AM wake anchor across 7 days/week",
        "Elimination of blue spectrum light past 20:30 PM",
        "Baseline resting heart rate measurement protocol",
      ],
    },
    {
      phase: "Phase 2: Metabolic Adaptation",
      timeline: "Days 31 – 60",
      milestone: "Mitochondrial Density Acceleration",
      deliverables: [
        "135 total minutes of weekly Zone 2 cardiovascular work",
        "Bi-weekly cold immersion at 52°F (3 min duration)",
        "Precision post-workout recovery nutritional timing",
      ],
    },
    {
      phase: "Phase 3: Executive Peak State",
      timeline: "Days 61 – 90",
      milestone: "Autonomous High-Yield Biomarker Equilibrium",
      deliverables: [
        "Continuous HRV monitoring showing 15% improvement",
        "Sustained 6 bpm drop in resting heart rate",
        "Quarterly comprehensive blood panel re-synthesis",
      ],
    },
  ],
  riskMitigation: [
    {
      risk: "Overtraining through excessive intensity during travel weeks",
      mitigation: "Automated deload protocol switches to active recovery walks if sleep score drops below 70.",
    },
    {
      risk: "Nutritional drift due to client dining schedules",
      mitigation: "Pre-event dietary anchoring rules with high-protein foundation.",
    },
  ],
  disclaimer: "This report is generated by PersonaFlow AI based on user-provided profile data and predefined algorithmic prompts. It is intended solely for educational, lifestyle, and executive strategy purposes and does not constitute formal medical diagnosis.",
  providerTelemetry: {
    provider: "OpenAI gpt-4o-mini",
    model: "gpt-4o-mini-2024-07-18",
    latencyMs: 342,
    tokens: { input: 1420, output: 890 },
    timestamp: "2026-09-15T00:00:00.000Z",
    cached: true,
  },
};

export default function PersonaFlowApp() {
  const [activeTab, setActiveTab] = useState<"studio" | "chat" | "cms" | "account">("studio");
  const [currentProfile, setCurrentProfile] = useState<CustomerProfile>(SAMPLE_PROFILES[0]);
  const [generatedReport, setGeneratedReport] = useState<PersonalizedReport | null>(INITIAL_REPORT);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [lastLatency, setLastLatency] = useState<number>(342);
  const [reportCount, setReportCount] = useState<number>(14);
  const [activeProvider, setActiveProvider] = useState<string>("OpenAI gpt-4o-mini");
  const [workflowStepIndex, setWorkflowStepIndex] = useState<number>(5);
  const [mounted, setMounted] = useState<boolean>(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Modals
  const [isBlueprintsOpen, setIsBlueprintsOpen] = useState<boolean>(false);
  const [isRoiOpen, setIsRoiOpen] = useState<boolean>(false);
  const [isChaosOpen, setIsChaosOpen] = useState<boolean>(false);
  const [chaosActive, setChaosActive] = useState<boolean>(false);

  // Live event logs
  const [logs, setLogs] = useState<LogEntry[]>([
    {
      id: "log_01",
      timestamp: "11:42:15 PM",
      type: "INGEST",
      message: `Ingested customer profile for ${SAMPLE_PROFILES[0].fullName} (${SAMPLE_PROFILES[0].email})`,
    },
    {
      id: "log_02",
      timestamp: "11:42:20 PM",
      type: "PRONOUN",
      message: `Deterministic pronoun matrix resolved: [they/them] · verb agreement [are/have/do] locked`,
    },
    {
      id: "log_03",
      timestamp: "11:42:35 PM",
      type: "AI",
      message: `Dual-model inference dispatched: Primary OpenAI gpt-4o-mini executed in 342ms`,
    },
    {
      id: "log_04",
      timestamp: "11:42:45 PM",
      type: "PDF",
      message: `Executive vector PDF synthesized: [PF-2026-9812] (3 insights, 3-phase roadmap, zero middle void)`,
    },
    {
      id: "log_05",
      timestamp: "11:42:55 PM",
      type: "WEBHOOK",
      message: `Multi-channel delivery armed: Resend SMTP + Twilio SMS alert queued`,
    },
  ]);

  const addLog = (type: LogEntry["type"], message: string) => {
    const newEntry: LogEntry = {
      id: `log_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }),
      type,
      message,
    };
    setLogs((prev) => [newEntry, ...prev.slice(0, 49)]);
  };

  const handleGenerateReport = async (
    profile: CustomerProfile,
    promptId: string,
    providerOverride?: "openai" | "gemini" | "rule"
  ) => {
    setIsGenerating(true);
    setWorkflowStepIndex(1);

    addLog("INGEST", `Processing intake for ${profile.fullName} [Category: ${profile.selectedCategory}]`);

    // Sequential step animation
    setTimeout(() => setWorkflowStepIndex(2), 600);
    setTimeout(() => {
      setWorkflowStepIndex(3);
      addLog("PRONOUN", `Pronoun guard verified: ${profile.pronouns} with exact subject-verb agreement`);
    }, 1200);

    try {
      const response = await fetch("/api/generate-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          profile,
          customPromptId: promptId,
          forceProvider: chaosActive ? "gemini" : providerOverride,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.report) {
        throw new Error(data.error || "Failed to synthesize report");
      }

      setWorkflowStepIndex(4);
      addLog("AI", `LLM generation successful via ${data.report.providerTelemetry.provider} in ${data.report.providerTelemetry.latencyMs}ms`);

      setTimeout(() => {
        setWorkflowStepIndex(5);
        addLog("PDF", `Vector PDF compiled for ${profile.fullName} [Code: ${data.report.reportCode}]`);
        addLog("WEBHOOK", `Automated delivery channels triggered (Email & SMS preferences verified)`);

        setGeneratedReport(data.report);
        setLastLatency(data.report.providerTelemetry.latencyMs);
        setActiveProvider(data.report.providerTelemetry.provider);
        setReportCount((c) => c + 1);
        setIsGenerating(false);
      }, 800);
    } catch (err: any) {
      console.error("Pipeline generation error:", err);
      addLog("AI", `Notice: Fallback activated - ${err.message}`);
      setIsGenerating(false);
      setWorkflowStepIndex(5);
    }
  };

  const handleQuickDemo = () => {
    setActiveTab("studio");
    handleGenerateReport(currentProfile, currentProfile.predefinedPromptId);
  };

  const handleSelectPresetProfile = (p: CustomerProfile) => {
    setCurrentProfile(p);
    addLog("INGEST", `Switched active customer profile to ${p.fullName} (${p.selectedCategory})`);
  };

  if (!mounted) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--color-bg)]">
        <div className="flex items-center gap-2 text-sm font-semibold text-blue-600 font-mono">
          <span className="h-2 w-2 rounded-full bg-blue-600 animate-ping" />
          Initializing PersonaFlow AI Cockpit...
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col bg-[var(--color-bg)] text-[var(--color-text-primary)]">
      {/* 1. Global Navigation Header */}
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        onQuickDemo={handleQuickDemo}
        onOpenBlueprints={() => setIsBlueprintsOpen(true)}
        onOpenRoi={() => setIsRoiOpen(true)}
        onOpenChaos={() => setIsChaosOpen(true)}
        chaosActive={chaosActive}
        isGenerating={isGenerating}
      />

      {/* 2. Bento KPIs (High-Density Metrics Bar) */}
      <BentoKpis
        lastLatency={lastLatency}
        reportCount={reportCount}
        providerName={activeProvider}
      />

      {/* 3. Hero & Quick Preset Bar */}
      <section className="py-6 border-b border-[var(--color-border)] bg-[var(--color-panel)]">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-950/40 dark:text-blue-300 dark:border-blue-800">
                  <Sparkles className="h-3.5 w-3.5" />
                  Turnkey Consumer AI Platform
                </span>
                <span className="text-xs text-[var(--color-text-muted)] font-mono">
                  v2.4 Production Build
                </span>
              </div>
              <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold tracking-tight text-[var(--color-text-primary)]">
                Autonomous Personalization &amp; PDF Delivery Engine
              </h1>
              <p className="text-xs sm:text-sm text-[var(--color-text-secondary)] mt-1 max-w-2xl">
                Synthesize customized intelligence dossiers from predefined prompts and customer
                profiles, enforce deterministic pronoun agreement, and manage dynamic CMS products
                without writing code.
              </p>
            </div>

            {/* Preset Profile Fast-Loader */}
            <div className="flex flex-col sm:flex-row sm:items-center gap-2 p-2 rounded-xl bg-[var(--color-panel-subtle)] border border-[var(--color-border)]">
              <span className="text-xs font-semibold text-[var(--color-text-muted)] uppercase tracking-wider px-2">
                Sample Profiles:
              </span>
              <div className="flex items-center gap-1.5 overflow-x-auto">
                {SAMPLE_PROFILES.map((p) => {
                  const isSelected = currentProfile.id === p.id;
                  return (
                    <button
                      key={p.id}
                      onClick={() => handleSelectPresetProfile(p)}
                      className={`px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${
                        isSelected
                          ? "bg-[var(--color-panel)] text-blue-600 shadow-sm border border-[var(--color-border)] font-semibold"
                          : "text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-panel)]/50"
                      }`}
                    >
                      {p.fullName.split(" ")[0]} ({p.pronouns})
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Main Operational Cockpit */}
      <main className="flex-1 py-8">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 space-y-8">
          {/* Animated SVG Workflow Pipeline */}
          <WorkflowCanvas
            onTriggerPipeline={handleQuickDemo}
            isGenerating={isGenerating}
            activeStepIndex={workflowStepIndex}
          />

          {/* Dynamic Tab Switcher Content */}
          {activeTab === "studio" && (
            <div className="space-y-8">
              {/* Studio Grid: Persona Configurator on Left, PDF Dossier Viewer on Right */}
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                {/* Left: Persona Studio Profile Builder */}
                <div className="lg:col-span-7 space-y-6">
                  <div className="p-4 rounded-xl bg-blue-50/60 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-900 text-xs text-blue-800 dark:text-blue-300 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Cpu className="h-4 w-4 text-blue-600 shrink-0" />
                      <span>
                        Active Engine: <strong>{activeProvider}</strong> with automatic sub-second fallback
                      </span>
                    </div>
                    {chaosActive && (
                      <span className="px-2 py-0.5 rounded text-xs font-bold bg-rose-600 text-white animate-pulse">
                        CHAOS FAILOVER ENGAGED
                      </span>
                    )}
                  </div>

                  <PersonaStudio
                    onGenerateReport={handleGenerateReport}
                    isGenerating={isGenerating}
                    generatedReport={generatedReport}
                    currentProfile={currentProfile}
                    setCurrentProfile={setCurrentProfile}
                  />
                </div>

                {/* Right: Polished PDF Dossier Preview */}
                <div className="lg:col-span-5">
                  <div className="sticky top-20">
                    {generatedReport ? (
                      <PdfReportPreview
                        report={generatedReport}
                        onLogEvent={(msg) => addLog("PDF", msg)}
                      />
                    ) : (
                    <div className="h-96 rounded-2xl border-2 border-dashed border-[var(--color-border)] flex flex-col items-center justify-center p-8 text-center bg-[var(--color-panel)]">
                      <div className="p-3 rounded-full bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400 mb-3">
                        <FileText className="h-6 w-6" />
                      </div>
                      <h4 className="text-sm font-semibold text-[var(--color-text-primary)]">
                        No Dossier Synthesized Yet
                      </h4>
                      <p className="text-xs text-[var(--color-text-muted)] max-w-sm mt-1">
                        Configure the customer profile on the left or select a sample preset,
                        then click &quot;Synthesize &amp; Compile PDF Dossier&quot; to execute real inference.
                      </p>
                    </div>
                  )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === "chat" && (
            <div className="max-w-4xl mx-auto">
              <ProfileAwareChatbot
                currentProfile={currentProfile}
                currentReport={generatedReport}
                onLogEvent={(msg) => addLog("AI", msg)}
              />
            </div>
          )}

          {activeTab === "cms" && (
            <CmsCatalogWorkbench
              onLogEvent={(msg) => addLog("CMS", msg)}
            />
          )}

          {activeTab === "account" && (
            <div className="max-w-4xl mx-auto">
              <AccountSecurityCenter
                currentProfile={currentProfile}
                onLogEvent={(msg) => addLog("SECURITY", msg)}
              />
            </div>
          )}

          {/* 5. Live Execution Telemetry & Endpoint cURL Drawer */}
          <ExecutionLogDrawer
            logs={logs}
            activeProvider={activeProvider}
            chaosMode={chaosActive}
          />
        </div>
      </main>

      {/* 6. Technical Specifications Footer */}
      <Footer
        onOpenBlueprints={() => setIsBlueprintsOpen(true)}
        onOpenRoi={() => setIsRoiOpen(true)}
        onOpenChaos={() => setIsChaosOpen(true)}
      />

      {/* Modals */}
      <BlueprintExporter
        isOpen={isBlueprintsOpen}
        onClose={() => setIsBlueprintsOpen(false)}
      />
      <RoiCostCalculator
        isOpen={isRoiOpen}
        onClose={() => setIsRoiOpen(false)}
      />
      <ChaosOutageSimulator
        isOpen={isChaosOpen}
        onClose={() => setIsChaosOpen(false)}
        chaosActive={chaosActive}
        onToggleChaos={(active) => {
          setChaosActive(active);
          if (active) {
            setActiveProvider("Google Gemini 2.0 Flash (Failover)");
            addLog("AI", "CHAOS ENGAGED: Primary OpenAI gpt-4o-mini cut; Gemini 2.0 Flash active");
          } else {
            setActiveProvider("OpenAI gpt-4o-mini");
            addLog("AI", "RESTORED: Primary OpenAI gpt-4o-mini returned to active status");
          }
        }}
        onInjectChaosLog={(msg) => addLog("AI", msg)}
      />
    </div>
  );
}
